name = "MEPSDatasets"
uuid = "ea2dce40-b9da-4d2f-8291-c5505fb52ee1"
authors = ["Roel Stappers <roels@met.no>"]
version = "0.1.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
